services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres:18-bookworm'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'supersecretpassword'
      POSTGRES_DB: 'rendezvous'
    volumes:
      - 'pgdata:/var/lib/postgresql'
volumes:
  pgdata:
