spring:
  application:
    name: rendezvous
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rendezvous
    username: postgres
    password: supersecretpassword
jwt:
  secret: supersecret394823-94893-19pfijewpifjdqeprjwjpewfjwpeitj2r43p9
  issuer: rendezvous
  expiry:
    access: 3600
logging:
  level:
    org.springframework.r2dbc: DEBUG